---
env:
  es6: true
  jest: true
  browser: true
  node: true

parser: "@typescript-eslint/parser"

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jsx-a11y/recommended
  - prettier/@typescript-eslint
  - prettier

plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
  - jsx-a11y

settings:
  react:
    version: detect
