version: "3.8"
services:
  web:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules/ # Use anonymous volume to ignore node_modules
