version: "3.8"
services:
  web:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - web_node_modules:/app/node_modules # ignore node_modules
volumes:
  web_node_modules:
